# OrganicHats VCV Rack Module
# Hi-hat synthesizer with choke logic

ifndef RACK_DIR
RACK_DIR ?= $(HOME)/Rack-SDK
endif

SOURCES += src/plugin.cpp
SOURCES += src/OrganicHats.cpp

DISTRIBUTABLES += res

include $(RACK_DIR)/plugin.mk
