# AngelGrain VCV Rack Module
# 32-voice granular delay processor

ifndef RACK_DIR
RACK_DIR ?= $(HOME)/Rack-SDK
endif

SOURCES += src/plugin.cpp
SOURCES += src/AngelGrain.cpp

DISTRIBUTABLES += res

include $(RACK_DIR)/plugin.mk
