# LushPad VCV Rack Module
# Polyphonic pad synthesizer with FM and reverb

ifndef RACK_DIR
RACK_DIR ?= $(HOME)/Rack-SDK
endif

SOURCES += src/plugin.cpp
SOURCES += src/LushPad.cpp

DISTRIBUTABLES += res

include $(RACK_DIR)/plugin.mk
