# DrumRoulette VCV Rack Module
# 8-voice randomizable synth drum kit

ifndef RACK_DIR
RACK_DIR ?= $(HOME)/Rack-SDK
endif

SOURCES += src/plugin.cpp
SOURCES += src/DrumRoulette.cpp

DISTRIBUTABLES += res

include $(RACK_DIR)/plugin.mk
