# Scatter VCV Rack Module
# Granular delay with pitch quantization

ifndef RACK_DIR
RACK_DIR ?= $(HOME)/Rack-SDK
endif

SOURCES += src/plugin.cpp
SOURCES += src/Scatter.cpp

DISTRIBUTABLES += res

include $(RACK_DIR)/plugin.mk
