# Drum808 VCV Rack Module
# 6-voice analog drum synthesizer

ifndef RACK_DIR
RACK_DIR ?= $(HOME)/Rack-SDK
endif

SOURCES += src/plugin.cpp
SOURCES += src/Drum808.cpp

DISTRIBUTABLES += res

include $(RACK_DIR)/plugin.mk
