# TapeAge VCV Rack Module
# Tape emulation with saturation, wow/flutter, noise

ifndef RACK_DIR
RACK_DIR ?= $(HOME)/Rack-SDK
endif

SOURCES += src/plugin.cpp
SOURCES += src/TapeAge.cpp

DISTRIBUTABLES += res

include $(RACK_DIR)/plugin.mk
